inherit_from:
  - lib/fuse_dev_tools/templates/.rubocop.yml
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - fuse-dev-tools.gemspec
