Rails/Output:
  Exclude:
    - lib/fuse_dev_tools/tasks/application_config.rb
Security/Eval:
  Exclude:
    - spec/support/stream_capture_helper.rb
Style/EvalWithLocation:
  Exclude:
    - spec/support/stream_capture_helper.rb
