Metrics/BlockLength:
  Exclude:
    - fuse-dev-tools.gemspec
    - spec/fuse_dev_tools/git_tools/commit_message_spec.rb
    - spec/fuse_dev_tools/git_tools/pull_request_validator_spec.rb

Metrics/MethodLength:
  Exclude:
    - lib/fuse_dev_tools/tasks/git_commands/commit_messages.rb

Rails/Exit:
  Exclude:
    - lib/fuse_dev_tools/tasks/git_commands/*.rb

Security/Eval:
  Exclude:
    - spec/support/stream_capture_helper.rb

Style/EvalWithLocation:
  Exclude:
    - spec/support/stream_capture_helper.rb
