inherit_from:
  - lib/fuse_dev_tools/templates/.rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - fuse-dev-tools.gemspec

Security/Eval:
  Exclude:
    - spec/support/stream_capture_helper.rb

Style/EvalWithLocation:
  Exclude:
    - spec/support/stream_capture_helper.rb
